using System.Runtime.CompilerServices;

[assembly: InternalsVisibleTo("S2Cognition.Integrations.AmazonWebServices.CloudWatch")]
[assembly: InternalsVisibleTo("S2Cognition.Integrations.AmazonWebServices.CloudWatch.Tests")]
[assembly: InternalsVisibleTo("S2Cognition.Integrations.AmazonWebServices.Core")]
[assembly: InternalsVisibleTo("S2Cognition.Integrations.AmazonWebServices.Core.Tests")]
[assembly: InternalsVisibleTo("S2Cognition.Integrations.AmazonWebServices.DynamoDb")]
[assembly: InternalsVisibleTo("S2Cognition.Integrations.AmazonWebServices.DynamoDb.Tests")]
[assembly: InternalsVisibleTo("S2Cognition.Integrations.Core")]
[assembly: InternalsVisibleTo("S2Cognition.Integrations.Core.Tests")]
[assembly: InternalsVisibleTo("S2Cognition.Integrations.Monday.Core")]
[assembly: InternalsVisibleTo("S2Cognition.Integrations.Monday.Core.Tests")]
[assembly: InternalsVisibleTo("S2Cognition.Integrations.NetSuite.Core")]
[assembly: InternalsVisibleTo("S2Cognition.Integrations.NetSuite.Core.Tests")]
[assembly: InternalsVisibleTo("S2Cognition.Integrations.Zoom.Core")]
[assembly: InternalsVisibleTo("S2Cognition.Integrations.Zoom.Core.Tests")]
[assembly: InternalsVisibleTo("S2Cognition.Integrations.S3")]
[assembly: InternalsVisibleTo("S2Cognition.Integrations.S3.Tests")]